### ISSUE TITLE
haus (3DS demo) freezing and graphical glitches

### ISSUE THREAD

**Issue by ualaa1** [burhanr13/ctremu#25]
First 3DS demo that I was able to boot without the emulator outright crashing. Demo from https://www.pouet.net/prod.php?which=95228
Freezes on this glitchy screen

![Image](https://github.com/user-attachments/assets/885f1c88-fe9e-4455-869e-0e1334714676)

[ctremu.log](https://github.com/user-attachments/files/19080339/ctremu.log)

This linked demo also seems to use the same engine and seems to have similar problems as well https://www.pouet.net/prod.php?which=94717

**Comment by burhanr13** [comment]
can you provide a log for one of the crashing demos

**Comment by ualaa1** [comment]
Sure
Here's one
From https://www.pouet.net/prod.php?which=97944
Crashes a few seconds into boot

[ctremu.log](https://github.com/user-attachments/files/19142212/ctremu.log)

**Comment by burhanr13** [comment]
also for the homebrew demo that didn't crash it looks like it requires the dsp firmware file. i can probably work around this by putting in a dummy file (since firmware isnt necessary on hle audio. can you try making an empty file at system/sdmc/3ds/dspfirm.cdc and see if it gets further?

**Comment by ualaa1** [comment]
I have also created a new file on the sdmc file called 3ds and inserted the dsp file there 
Tanuki3DS\system\sdmc\3DS
Music plays, but the graphics seem to stop rendering after some time. Also, it seems only the outline of the graphics are rendered

[ctremu.log](https://github.com/user-attachments/files/19146859/ctremu.log)

https://github.com/user-attachments/assets/9094c21a-4f6b-4267-bd9a-c13f7c5e73fd

**Comment by burhanr13** [comment]
I have implemented shared font relocation in the latest build. Can you try running those demos which were crashing earlier?

**Comment by ualaa1** [comment]
For some reason, the nightly I grabbed based on commit [d16b854](https://github.com/burhanr13/Tanuki3DS/commit/d16b854b9eba58d861d366fc3610c8c4d4ca8836) crashes instantly whenever anything gets loaded. If you want, I can make a separate issue regarding that. I am running on Windows 11 x64. 
Here is a log for one of the crashes

[ctremu.log](https://github.com/user-attachments/files/19332668/ctremu.log)

**Comment by burhanr13** [comment]
that should be fixed now in the newest build. (was an issue with calling conventions)

**Comment by ualaa1** [comment]
Most of them seem to run or at the very least not crash, however https://www.pouet.net/prod.php?which=67668 still crashes.

[ctremu.log](https://github.com/user-attachments/files/19359394/ctremu.log)

**Comment by burhanr13** [comment]
this demo is fixed now (though note it does not have audio because it does not use DSP sound)

**Comment by ualaa1** [comment]
https://www.pouet.net/prod.php?which=66607 [ctremu.log](https://github.com/user-attachments/files/19382799/ctremu.log)
Boots to black screen


https://www.pouet.net/prod.php?which=98117 and https://www.pouet.net/prod.php?which=97880 -Seems to use same engine as both seem to have the exact same issue. Only credits are the bottom are rendered. No other graphics and sounds are rendered.

[ctremu.log](https://github.com/user-attachments/files/19382871/ctremu.log)

The rest of the demos that were tested all boot and render graphics and sound, albeit graphics often look distorted and lack detail
